reserved_names = [
	'arithmeticerror', 'assertionerror', 'attributeerror', 'baseexception', 'blockingioerror', 'brokenpipeerror',
	'buffererror', 'byteswarning', 'childprocesserror', 'connectionabortederror', 'connectionerror',
	'connectionrefusederror', 'connectionreseterror', 'deprecationwarning', 'eoferror', 'ellipsis', 'environmenterror',
	'exception', 'false', 'fileexistserror', 'filenotfounderror', 'floatingpointerror', 'futurewarning',
	'generatorexit', 'ioerror', 'importerror', 'importwarning', 'indentationerror', 'indexerror', 'interruptederror',
	'isadirectoryerror', 'keyerror', 'keyboardinterrupt', 'lookuperror', 'memoryerror', 'modulenotfounderror',
	'nameerror', 'none', 'notadirectoryerror', 'notimplemented', 'notimplementederror', 'oserror', 'overflowerror',
	'pendingdeprecationwarning', 'permissionerror', 'processlookuperror', 'recursionerror', 'referenceerror',
	'resourcewarning', 'runtimeerror', 'runtimewarning', 'stopasynciteration', 'stopiteration', 'syntaxerror',
	'syntaxwarning', 'systemerror', 'systemexit', 'taberror', 'timeouterror', 'true', 'typeerror', 'unboundlocalerror',
	'unicodedecodeerror', 'unicodeencodeerror', 'unicodeerror', 'unicodetranslateerror', 'unicodewarning',
	'userwarning', 'valueerror', 'warning', 'windowserror', 'zerodivisionerror', '__build_class__', '__debug__',
	'__doc__', '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'all', 'any', 'ascii', 'bin',
	'bool', 'breakpoint', 'bytearray', 'bytes', 'callable', 'chr', 'classmethod', 'compile', 'complex', 'copyright',
	'credits', 'delattr', 'dict', 'dir', 'divmod', 'enumerate', 'eval', 'exec', 'exit', 'filter', 'float', 'format',
	'frozenset', 'getattr', 'globals', 'hasattr', 'hash', 'help', 'hex', 'id', 'input', 'int', 'isinstance',
	'issubclass', 'iter', 'len', 'license', 'list', 'locals', 'map', 'max', 'memoryview', 'min', 'next', 'object',
	'oct', 'open', 'ord', 'pow', 'print', 'property', 'quit', 'range', 'repr', 'reversed', 'round', 'set', 'setattr',
	'slice', 'sorted', 'staticmethod', 'str', 'sum', 'super', 'tuple', 'type', 'vars', 'zip'
]
